import type { Task } from "@/lib/types"

const DEFAULT_AVATAR = "/images/img-20251219-wa0001.jpg"

export const initialTasks: Task[] = [
  {
    id: "1",
    title: "Design UI Mockups",
    description:
      "Create wireframes and mockups for the main app screens including dashboard, user profile, and settings pages",
    status: "todo",
    priority: "high",
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Alex Chen",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 20,
    comments: 3,
    tags: ["design", "frontend"],
    timeEstimate: 8,
  },
  {
    id: "2",
    title: "Setup Backend API",
    description: "Initialize Express server and create basic endpoints for user authentication and data retrieval",
    status: "in-progress",
    priority: "medium",
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Jamie Smith",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 45,
    comments: 2,
    tags: ["backend", "api"],
    timeEstimate: 12,
  },
  {
    id: "3",
    title: "Implement Authentication",
    description: "Add user login and registration functionality with JWT tokens and secure password storage",
    status: "in-progress",
    priority: "high",
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Taylor Wong",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 60,
    comments: 5,
    tags: ["security", "backend"],
    timeEstimate: 10,
  },
  {
    id: "4",
    title: "Write Documentation",
    description: "Document API endpoints and usage instructions for the development team and future contributors",
    status: "todo",
    priority: "low",
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Morgan Lee",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 0,
    comments: 0,
    tags: ["documentation"],
    timeEstimate: 6,
  },
  {
    id: "5",
    title: "Create Landing Page",
    description: "Design and implement the project landing page with key features and call-to-action sections",
    status: "done",
    priority: "medium",
    deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Casey Johnson",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 100,
    comments: 7,
    tags: ["design", "frontend"],
    timeEstimate: 8,
  },
  {
    id: "6",
    title: "Database Schema Design",
    description: "Create the database schema with proper relationships between users, projects, and tasks",
    status: "done",
    priority: "high",
    deadline: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Jamie Smith",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 100,
    comments: 4,
    tags: ["database", "backend"],
    timeEstimate: 5,
  },
  {
    id: "7",
    title: "Implement Search Functionality",
    description: "Add search capability across projects and tasks with filtering options",
    status: "todo",
    priority: "medium",
    deadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Alex Chen",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 0,
    comments: 1,
    tags: ["feature", "frontend"],
    timeEstimate: 6,
  },
  {
    id: "8",
    title: "Mobile Responsive Design",
    description: "Ensure the application works well on mobile devices with appropriate layouts",
    status: "in-progress",
    priority: "high",
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Casey Johnson",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 35,
    comments: 2,
    tags: ["design", "frontend"],
    timeEstimate: 10,
  },
  {
    id: "9",
    title: "User Testing",
    description: "Conduct user testing sessions and collect feedback for improvements",
    status: "todo",
    priority: "medium",
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: "Morgan Lee",
    assigneeAvatar: DEFAULT_AVATAR,
    progress: 0,
    comments: 0,
    tags: ["testing", "research"],
    timeEstimate: 12,
  },
]
